### ISSUE TITLE
Type hash needs a name for EIP712

### ISSUE THREAD

**Issue by dan13ram** [raid-guild/wpokt-hyperlane-contracts#1]
https://github.com/raid-guild/wpokt-hyperlane-contracts/blob/e84108fa5476aec06813e84e9c6a2c09c787e5e5/src/WarpISM.sol#L22

example: 
```sol
bytes32 constant MAIL_TYPEHASH = keccak256("Mail(address from,address to,string contents)");
```

Notice the type name "Mail" surrounding the inner data types. 
Ref: https://eips.ethereum.org/EIPS/eip-712

**Comment by dan13ram** [comment]
Also the decoding of the message in `getDigest` is incorrect, the correct way is to use the helper methods from `Message.sol`

https://github.com/raid-guild/wpokt-hyperlane-contracts/blob/26440324ee6f81e140b45bc1f56c78edc840e438/src/WarpISM.sol#L46

You are using `abi.decode` but this will only work if we have used `abi.encode` earlier. But it's `abi.encodePacked` so this fails.

**Comment by dan13ram** [comment]
@St4rgarden  I've made these changes in my fork at https://github.com/dan13ram/wpokt-hyperlane-contracts/blob/main/src/WarpISM.sol if you want to take a look.

**Comment by St4rgarden** [comment]
> Also the decoding of the message in `getDigest` is incorrect, the correct way is to use the helper methods from `Message.sol`
> 
> https://github.com/raid-guild/wpokt-hyperlane-contracts/blob/26440324ee6f81e140b45bc1f56c78edc840e438/src/WarpISM.sol#L46
> 
> You are using `abi.decode` but this will only work if we have used `abi.encode` earlier. But it's `abi.encodePacked` so this fails.

Yes thanks this is quite helpful I was just about to comb all the message and digest construction because we're ready to get signatures validating today.

**Comment by dan13ram** [comment]
> Yes thanks this is quite helpful I was just about to comb all the message and digest construction because we're ready to get signatures validating today.

Of course! It took me a while to figure out why the signatures the validators created were failing 😵‍💫
